// backend/constants/errorCodes.js
// Centralised error code registry used across all API responses

export const ErrorCodes = {
  // Authentication
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_NO_TOKEN: 'AUTH_NO_TOKEN',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',

  // OTP
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',

  // Registration
  REG_EMAIL_EXISTS: 'REG_EMAIL_EXISTS',
  REG_PHONE_EXISTS: 'REG_PHONE_EXISTS',
  REG_USERNAME_EXISTS: 'REG_USERNAME_EXISTS',
  REG_INVALID_DATA: 'REG_INVALID_DATA',

  // User / Profile
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_BANNED: 'USER_BANNED',

  // Driver
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DRIVER_OFFLINE: 'DRIVER_OFFLINE',
  DRIVER_NOT_APPROVED: 'DRIVER_NOT_APPROVED',
  DRIVER_BANNED: 'DRIVER_BANNED',
  DRIVER_ALREADY_ON_RIDE: 'DRIVER_ALREADY_ON_RIDE',

  // Ride
  RIDE_NOT_FOUND: 'RIDE_NOT_FOUND',
  RIDE_ALREADY_ACCEPTED: 'RIDE_ALREADY_ACCEPTED',
  RIDE_ALREADY_COMPLETED: 'RIDE_ALREADY_COMPLETED',
  RIDE_ALREADY_CANCELLED: 'RIDE_ALREADY_CANCELLED',
  RIDE_OTP_INVALID: 'RIDE_OTP_INVALID',
  RIDE_CREATE_FAILED: 'RIDE_CREATE_FAILED',
  RIDE_NO_DRIVER_AVAILABLE: 'RIDE_NO_DRIVER_AVAILABLE',

  // Wallet
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_LOW_BALANCE: 'WALLET_LOW_BALANCE',
  WALLET_INVALID_AMOUNT: 'WALLET_INVALID_AMOUNT',
  WALLET_TRANSACTION_FAILED: 'WALLET_TRANSACTION_FAILED',

  // Payment
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_DONE: 'PAYMENT_ALREADY_DONE',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_WEBHOOK_INVALID',
  PAYMENT_REFUND_FAILED: 'PAYMENT_REFUND_FAILED',

  // Notification
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',

  // Upload
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_SIZE_EXCEEDED: 'UPLOAD_SIZE_EXCEEDED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // Geoapify / Maps
  GEO_ROUTE_FAILED: 'GEO_ROUTE_FAILED',
  GEO_GEOCODE_FAILED: 'GEO_GEOCODE_FAILED',

  // Database
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DB_NOT_FOUND: 'DB_NOT_FOUND',
  DB_DUPLICATE_ENTRY: 'DB_DUPLICATE_ENTRY',

  // Server
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export default ErrorCodes;
