/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RideTypeRouteImport } from './routes/ride-type'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DriverAssignedRouteImport } from './routes/driver-assigned'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RiderHomeRouteImport } from './routes/rider/home'
import { Route as DriverVerificationRouteImport } from './routes/driver/verification'
import { Route as DriverRequestsRouteImport } from './routes/driver/requests'
import { Route as DriverProfileRouteImport } from './routes/driver/profile'
import { Route as DriverOtpRouteImport } from './routes/driver/otp'
import { Route as DriverHomeRouteImport } from './routes/driver/home'
import { Route as DriverEarningsRouteImport } from './routes/driver/earnings'
import { Route as DriverDashboardRouteImport } from './routes/driver/dashboard'
import { Route as DriverArrivedRouteImport } from './routes/driver/arrived'
import { Route as DriverActiveRouteImport } from './routes/driver/active'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRidesRouteImport } from './routes/admin/rides'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RideTypeRoute = RideTypeRouteImport.update({
  id: '/ride-type',
  path: '/ride-type',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverAssignedRoute = DriverAssignedRouteImport.update({
  id: '/driver-assigned',
  path: '/driver-assigned',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderHomeRoute = RiderHomeRouteImport.update({
  id: '/rider/home',
  path: '/rider/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverVerificationRoute = DriverVerificationRouteImport.update({
  id: '/driver/verification',
  path: '/driver/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRequestsRoute = DriverRequestsRouteImport.update({
  id: '/driver/requests',
  path: '/driver/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOtpRoute = DriverOtpRouteImport.update({
  id: '/driver/otp',
  path: '/driver/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHomeRoute = DriverHomeRouteImport.update({
  id: '/driver/home',
  path: '/driver/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver/earnings',
  path: '/driver/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver/dashboard',
  path: '/driver/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverArrivedRoute = DriverArrivedRouteImport.update({
  id: '/driver/arrived',
  path: '/driver/arrived',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverActiveRoute = DriverActiveRouteImport.update({
  id: '/driver/active',
  path: '/driver/active',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRidesRoute = AdminRidesRouteImport.update({
  id: '/admin/rides',
  path: '/admin/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/confirm': typeof ConfirmRoute
  '/dashboard': typeof DashboardRoute
  '/driver-assigned': typeof DriverAssignedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/register': typeof RegisterRoute
  '/ride-type': typeof RideTypeRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/driver/active': typeof DriverActiveRoute
  '/driver/arrived': typeof DriverArrivedRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/otp': typeof DriverOtpRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/verification': typeof DriverVerificationRoute
  '/rider/home': typeof RiderHomeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/confirm': typeof ConfirmRoute
  '/dashboard': typeof DashboardRoute
  '/driver-assigned': typeof DriverAssignedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/register': typeof RegisterRoute
  '/ride-type': typeof RideTypeRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/driver/active': typeof DriverActiveRoute
  '/driver/arrived': typeof DriverArrivedRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/otp': typeof DriverOtpRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/verification': typeof DriverVerificationRoute
  '/rider/home': typeof RiderHomeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/confirm': typeof ConfirmRoute
  '/dashboard': typeof DashboardRoute
  '/driver-assigned': typeof DriverAssignedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/register': typeof RegisterRoute
  '/ride-type': typeof RideTypeRoute
  '/search': typeof SearchRoute
  '/searching': typeof SearchingRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/wallet': typeof WalletRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/driver/active': typeof DriverActiveRoute
  '/driver/arrived': typeof DriverArrivedRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/otp': typeof DriverOtpRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/verification': typeof DriverVerificationRoute
  '/rider/home': typeof RiderHomeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completed'
    | '/confirm'
    | '/dashboard'
    | '/driver-assigned'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/login'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/payment'
    | '/profile'
    | '/rating'
    | '/register'
    | '/ride-type'
    | '/search'
    | '/searching'
    | '/settings'
    | '/tracking'
    | '/wallet'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rides'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/driver/active'
    | '/driver/arrived'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/otp'
    | '/driver/profile'
    | '/driver/requests'
    | '/driver/verification'
    | '/rider/home'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completed'
    | '/confirm'
    | '/dashboard'
    | '/driver-assigned'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/login'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/payment'
    | '/profile'
    | '/rating'
    | '/register'
    | '/ride-type'
    | '/search'
    | '/searching'
    | '/settings'
    | '/tracking'
    | '/wallet'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rides'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/driver/active'
    | '/driver/arrived'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/otp'
    | '/driver/profile'
    | '/driver/requests'
    | '/driver/verification'
    | '/rider/home'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/completed'
    | '/confirm'
    | '/dashboard'
    | '/driver-assigned'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/login'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/payment'
    | '/profile'
    | '/rating'
    | '/register'
    | '/ride-type'
    | '/search'
    | '/searching'
    | '/settings'
    | '/tracking'
    | '/wallet'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rides'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verifications'
    | '/driver/active'
    | '/driver/arrived'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/otp'
    | '/driver/profile'
    | '/driver/requests'
    | '/driver/verification'
    | '/rider/home'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletedRoute: typeof CompletedRoute
  ConfirmRoute: typeof ConfirmRoute
  DashboardRoute: typeof DashboardRoute
  DriverAssignedRoute: typeof DriverAssignedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  RatingRoute: typeof RatingRoute
  RegisterRoute: typeof RegisterRoute
  RideTypeRoute: typeof RideTypeRoute
  SearchRoute: typeof SearchRoute
  SearchingRoute: typeof SearchingRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
  WalletRoute: typeof WalletRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminRidesRoute: typeof AdminRidesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  DriverActiveRoute: typeof DriverActiveRoute
  DriverArrivedRoute: typeof DriverArrivedRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHomeRoute: typeof DriverHomeRoute
  DriverOtpRoute: typeof DriverOtpRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverRequestsRoute: typeof DriverRequestsRoute
  DriverVerificationRoute: typeof DriverVerificationRoute
  RiderHomeRoute: typeof RiderHomeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride-type': {
      id: '/ride-type'
      path: '/ride-type'
      fullPath: '/ride-type'
      preLoaderRoute: typeof RideTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-assigned': {
      id: '/driver-assigned'
      path: '/driver-assigned'
      fullPath: '/driver-assigned'
      preLoaderRoute: typeof DriverAssignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/home': {
      id: '/rider/home'
      path: '/rider/home'
      fullPath: '/rider/home'
      preLoaderRoute: typeof RiderHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/verification': {
      id: '/driver/verification'
      path: '/driver/verification'
      fullPath: '/driver/verification'
      preLoaderRoute: typeof DriverVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/requests': {
      id: '/driver/requests'
      path: '/driver/requests'
      fullPath: '/driver/requests'
      preLoaderRoute: typeof DriverRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/otp': {
      id: '/driver/otp'
      path: '/driver/otp'
      fullPath: '/driver/otp'
      preLoaderRoute: typeof DriverOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/home': {
      id: '/driver/home'
      path: '/driver/home'
      fullPath: '/driver/home'
      preLoaderRoute: typeof DriverHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/driver/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/driver/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/arrived': {
      id: '/driver/arrived'
      path: '/driver/arrived'
      fullPath: '/driver/arrived'
      preLoaderRoute: typeof DriverArrivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/active': {
      id: '/driver/active'
      path: '/driver/active'
      fullPath: '/driver/active'
      preLoaderRoute: typeof DriverActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rides': {
      id: '/admin/rides'
      path: '/admin/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AdminRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletedRoute: CompletedRoute,
  ConfirmRoute: ConfirmRoute,
  DashboardRoute: DashboardRoute,
  DriverAssignedRoute: DriverAssignedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  RatingRoute: RatingRoute,
  RegisterRoute: RegisterRoute,
  RideTypeRoute: RideTypeRoute,
  SearchRoute: SearchRoute,
  SearchingRoute: SearchingRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
  WalletRoute: WalletRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminRidesRoute: AdminRidesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  DriverActiveRoute: DriverActiveRoute,
  DriverArrivedRoute: DriverArrivedRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHomeRoute: DriverHomeRoute,
  DriverOtpRoute: DriverOtpRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverRequestsRoute: DriverRequestsRoute,
  DriverVerificationRoute: DriverVerificationRoute,
  RiderHomeRoute: RiderHomeRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
